# Generated by Django 6.0.6 on 2026-06-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importanomaly',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
