# Generated by Django 6.0.6 on 2026-06-13 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_importanomaly_raw_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='core.group'),
        ),
    ]
